In [57]:
import pandas as pd
import requests
import time

#on check le nombre max d'annonces

url = 'https://www.apec.fr/cms/webservices/rechercheOffre'
myjson = {"lieux":[],"fonctions":[],
          "statutPoste":[],
          "typesContrat":[],"typesConvention":[],
          "niveauxExperience":["101881"],
          "idsEtablissement":[],"secteursActivite":[],
          "idNomZonesDeplacement":[],
          "positionNumbersExcluded":[],
          "typeClient":"CADRE","sorts":[{"type":"SCORE","direction":"DESCENDING"}],
          "pagination":{"range":20,"startIndex":20},"activeFiltre":True,
          "pointGeolocDeReference":{"distance":0},
          "motsCles":"data analyst"}
x = requests.post(url, json = myjson)
y = x.text
liste_totale =[]

nb_job_total = int(y[-4:-1])
nb_job_total

for i in range((nb_job_total//100)+1):
    myjson_total = {"lieux":[],
                "fonctions":[],
                "statutPoste":[],
                "typesContrat":[],
                "typesConvention":[],
                "niveauxExperience":["101881"],
                "idsEtablissement":[],
                "secteursActivite":[],
                "idNomZonesDeplacement":[],
                "positionNumbersExcluded":[],
                "typeClient":"CADRE","sorts":[{"type":"SCORE","direction":"DESCENDING"}],
                "pagination":{"range":100,"startIndex":i*100},"activeFiltre":True,
                "pointGeolocDeReference":{"distance":0},"motsCles":"data analyst"}
    x = requests.post(url, json = myjson_total)
    split = x.headers["X-Search-Results"].split()
    liste_totale += split
    

df = pd.DataFrame(columns =['intitule','nomCompteEtablissement','idNomTypeContrat','idNomNiveauExperience','texteHtmlProfil','texteHtmlEntreprise','texteHtml','salaireTexte'])
liste_lien =[]


for i in liste_totale:
    data_offre = "https://www.apec.fr/cms/webservices/offre/public?numeroOffre="+i
    liste_lien.append(data_offre)

for i in liste_lien:
    data = requests.get(i,).json()
    item_offre=[]
    time.sleep(0.5)
    print("tick")
    for j in ['intitule','nomCompteEtablissement','idNomTypeContrat','idNomNiveauExperience','texteHtmlProfil','texteHtmlEntreprise','texteHtml','salaireTexte']:
        try:
            item_offre.append(data[j])
        except KeyError:
            item_offre.append("None")
        
    df.loc[len(df)] = item_offre

tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick
tick

In [58]:
df

,intitule,nomCompteEtablissement,idNomTypeContrat,idNomNiveauExperience,texteHtmlProfil,texteHtmlEntreprise,texteHtml,salaireTexte
0,Data Analyst F/H,FED IT,101888,597152,<p>Issu d'une formation relative à l'analyse d...,"<p>Camille Bernard, consultante chez Fed IT, c...","<p><strong>A ce titre, vos missions sont les s...",38 - 45 k€ brut annuel
1,Data Analyst F/H,KERISTO,101888,597151,<p>Vous êtes de formation supérieure (BAC+5) e...,<p>Keristo est une jeune société de conseil av...,"<p>En tant que Data Analyst, vos missions sont...",A négocier
2,Data Analyst F/H,KERISTO,101888,597151,<p>Vous êtes de formation supérieure (BAC+5) e...,<p>Keristo est une jeune société de conseil av...,"<p>En tant que Data Analyst, vos missions sont...",A négocier
3,Data Analyst F/H,UNLCK,101888,597152,<p><strong>Profil</strong></p><p>Vous êtes dip...,"<p>Acteur indépendant du recrutement tech, UNL...",<p><strong>Contexte</strong></p><p>Vous êtes D...,40 - 50 k€ brut annuel
4,Data analyst F/H,LV TECHNOLOGIES,101888,597152,"<p>- De formation Bac +2/5 BTS ou DUT, u...",<p>Nous recrutons pour le compte de notre clie...,<p>Vous serez rattaché/e au chief data officer...,40 - 42 k€ brut annuel
...,...,...,...,...,...,...,...,...
211,Analyste Données et Reporting F/H,SudOuestJob,101888,200269,De formation Bac +3 à Bac +5 dans l'analyse de...,Lectra développe des solutions premium qui don...,Entreprise transnationale de 1 700 collaborate...,A négocier
212,Analyste Bi Senior - Consultant Power Bi - Qli...,Cadreo,101888,200269,- De formation Bac +5 (ingénieur ou équivalent...,Alliance Automotive Group France est un acteur...,Acteur majeur de la Distribution de pièces de ...,A négocier
213,Responsable service client - Prévoyance F/H,GIE DE PREVOYANCE SOCIALE,101888,597152,<p>Vous possédez une expérience significative ...,"<p>Fondé en 1970, le GIEPS (GIE de Prévoyance ...",<p>Rattaché(e) au Responsable Opérationnel Pré...,40 - 43 k€ brut annuel
214,Chargé de planification F/H,ADMIRAL INTERMEDIARY SERVICES SA,101888,200269,"<p>Chez L'olivier, on est bien sûr intéressé p...","<p>Vous nous connaissez peut-être déjà, mais s...",<p>Votre mission si vous l'acceptez :<br /><br...,A négocier
215,CHARGE DES STATISTIQUES ET PERFORMANCE - TOURS...,DOMITYS SAS,101888,597152,<p> </p><p><br />De formation statisticienne o...,<p> </p><p><br />Tellement plus à vivre quand ...,<p> </p><p><br />Rattaché à la Directrice Mark...,30 - 33 k€ brut annuel

In [61]:
df.to_csv("data_apec.csv")